In [1]:
#import numpy 
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
#1.) How many negative numbers are there?

#bring in array, look for where values are less than 0
a[a<0] 
#how many values were returned from above
len(a[a<0])

#or you can do .shape
a[a < 0].shape[0]
#There are 4 negative numbers

4

In [6]:
#2.) How many positive numbers are there?

#bring in array, and return values that are greater than 0 (because 0 isn't postitive)
a[a>0]

#how many values were returned
len(a[a>0])
a[a > 0].shape[0]
#There are 5 positive numbers

5

In [8]:
#3.) How many even positive numbers are there?

#make a new list, and append values that meet criteria
array_with_positive_even_numbers = []
for n in a:
    if n>0 and n%2 ==0:
        array_with_positive_even_numbers.append(n)
        
#len will tell us how many values are in our new list
len(array_with_positive_even_numbers)

#There are 3 numbers that are both even and positive in this array.

3

In [21]:
#4.) If you were to add 3 to each data point, how many positive numbers would there be?

#make a new list to contain new positive numbers
new_list = []

#add 3 to each number in our array 'a'
add_3_to_array = [n+3 for n in a]

#append into new list if number is positive
for n in add_3_to_array:
    if n>0:
        new_list.append(n)
#len of new list will give us how many entries are in it.
len(new_list)
#There would be 10 positive numbers

10

In [13]:
#5.) If you squared each number, what would the new mean and standard deviation be?

#square each number in array 'a'
squared_numbers = [n**2 for n in a]
print(squared_numbers)

#turn squared_numbers into a numpy array
num_squared = np.array(squared_numbers)

#now we can use .mean and .std()
print(num_squared.mean())
print(num_squared.std())
#The new mean is 74, and new standard deviation is 144.02

[16, 100, 144, 529, 4, 1, 0, 0, 0, 36, 9, 49]
74.0
144.0243035046516


In [15]:
#6.) A common statistical operation on a dataset is centering. 
#This means to adjust the data such that the mean of the data is 0. 
#This is done by subtracting the mean from each data point. Center the data set.

#finding the mean of our array
a.mean()
#a.mean() = 3

#subtract all values in our array by our mean, or 3
subt_three = [n-a.mean() for n in a]

#turn it into an array so we can calculate .mean() to be sure it is 0
centered_array = np.array(subt_three)
print(centered_array)
print(centered_array.mean())


[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]
0.0


In [44]:
#7.) Calculate the z-score for each data point. Recall that the z-score is given by: z = (x - mean)/stddev

#make a new list to contain our z scores
z_score_list = []

#calculate z score for every data point in our array
z_score = [n-a.mean()//(a.std()) for n in a]

#turn it into an array
z_score_array = np.array(z_score)
print (z_score_array)

[ 4. 10. 12. 23. -2. -1.  0.  0.  0. -6.  3. -7.]


In [46]:
#unless you didn't want to turn it into an array, here's a shorter way of doing it.
z_score = [n-a.mean()//(a.std()) for n in a]
z_score

print(z_score)
#The z-scores are [4.0, 10.0, 12.0, 23.0, -2.0, -1.0, 0.0, 0.0, 0.0, -6.0, 3.0, -7.0]

[4.0, 10.0, 12.0, 23.0, -2.0, -1.0, 0.0, 0.0, 0.0, -6.0, 3.0, -7.0]


<br>

### Numpy Exercises Part 1

In [16]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
#Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
print(sum_of_a)

# sum(a) is 55

55


In [20]:
 #Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
min_of_a
# min(a) is 1

1

In [21]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a
#max(a) is 10

10

In [56]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum(a)/len(a)
mean_of_a
#The mean_of_a is 5.5

5.5

In [89]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

#start product_of_a at 1, the first number in our list
product_of_a = 1

#as it goes through the list, product_of_a will change values, and continue multiplying onto the next value
for n in a:
    product_of_a = product_of_a * n
product_of_a
# the product_of_a is 3,628,800

3628800

In [67]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [n**2 for n in a]
squares_of_a
# The squares_of_a is [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [77]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = []
for n in a:
    if n%2 != 0:
        odds_in_a.append(n)

odds_in_a
#odds_in_a holds [1, 3, 5, 7, 9]

[1, 3, 5, 7, 9]

In [78]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = []
for n in a:
    if n%2 == 0:
        evens_in_a.append(n)
evens_in_a
#evens_in_a holds [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]

In [23]:
# Setup 2 - a matrix
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [24]:
#let's turn it into an array
b = np.array(b)

In [82]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

#add up values in each of b's rows
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
#------------------------------Refactor 
#turn b into a numpy array
b = np.array(b)

#sum it
sum_of_b = b.sum()
sum_of_b
#Sum_of_b is 33

33

In [25]:
# Exercise 2 - refactor the following to use numpy. aka find the min. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

#------------------------------Refactor 
#The min_of_b is 3
min_of_b = b.min()
min_of_b

3

In [85]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy. aka find the max
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

#------------------------------Refactor 
#The max_of_b is 8
max_of_b = b.max()
max_of_b

8

In [86]:
# Exercise 4 - refactor the following using numpy to find the mean of b. aka find the mean
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

#------------------------------Refactor 
#mean_of_b is 5.5 
mean_of_b = b.mean()
mean_of_b

5.5

In [88]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
#product_of_b is equal to 20160

#------------------------------Refactor 
product_of_b = b.prod()
product_of_b
        

20160

In [98]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
#squares_of_b returns array([[ 9, 16, 25],
       #[36, 49, 64]])

#------------------------------Refactor 
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [102]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

#------------------------------Refactor 
# odds_in b are ([3,5,7])            
step_1 = b % 2
step_2 = step_1 != 0
odds_in_b = b[step_2]

odds_in_b

array([3, 5, 7])

In [103]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

#------------------------------Refactor 
#evens_in_b are ([4, 6, 8])
step_1 = b % 2
step_2 = step_1 == 0
evens_in_b = b[step_2]

evens_in_b

array([4, 6, 8])

In [116]:
# Exercise 9 - print out the shape of the array b.

print(np.shape(b))

(2, 3)


In [115]:
# Exercise 10 - transpose the array b.
print(np.transpose(b))

[[3 6]
 [4 7]
 [5 8]]


In [121]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
print(np.reshape(b, (1,6)))

[[3 4 5 6 7 8]]


In [122]:
#Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
print(np.reshape(b, (6,1)))

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [27]:
## Setup 3 -- another matrix!
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


In [28]:
#turning it into a numpy array
c = np.array(c)

In [130]:
# Exercise 1 - Find the min, max, sum, and product of c.
print("The min of c is ", c.min())
print("The max of c is ", c.max())
print("The sum of c is ", c.sum())
print("The product of c is ", np.product(c))

The min of c is  1
The max of c is  9
The sum of c is  45
The product of c is  362880


In [131]:
# Exercise 2 - Determine the standard deviation of c.
print("The standard deviation of c is ", c.std())

The standard deviation of c is  2.581988897471611


In [39]:
c.shape[0]*c.shape[1]

9

In [42]:
# Exercise 3 - Determine the variance of c.
# find the mean which is 5
c.mean()
#subtract each number from the mean
c_minus_mean = [n-c.mean() for n in c]
c_minus_mean
#square the result
squared_c_result = np.array(c_minus_mean)
#add the results
squared_c_result.sum()

#divide by entries
c_needs_multiplying = np.shape(c)
c_needs_multiplying = list(c_needs_multiplying)
c_needs_multiplying = np.array(c_needs_multiplying)
number_of_entries = c_needs_multiplying.prod()

print(squared_c_result.sum()/number_of_entries)
#Variance for c is 0

0.0


In [9]:
# Exercise 4 - Print out the shape of the array c
np.shape(c)
print(np.shape(c))

(3, 3)


In [12]:
# Exercise 5 - Transpose c and print out transposed result.
np.transpose(c)
print(np.transpose(c))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)
print(np.dot(c,c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [22]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
(np.transpose(c)*c).sum()

print((np.transpose(c)*c).sum())

261


In [46]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
c2_array = np.transpose(c)
(c2_array*c).prod()
print((c2_array*c).prod())

131681894400


In [49]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d=np.array(d)

In [51]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [52]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [53]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [60]:
# Exercise 4 - Find all the negative numbers in d
set(d[d<0])

d[d<0]

array([-90, -30, -45, -45])

In [61]:
# Exercise 5 - Find all the positive numbers in d
set(d[d>0])
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [66]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [67]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))

11

In [69]:
# Exercise 8 - Print out the shape of d.
np.shape(d)

(3, 6)

In [75]:
# Exercise 9 - Transpose and then print out the shape of d.
transpose_d = np.transpose(d)
transpose_d = np.array(transpose_d)
np.shape(transpose_d)

(6, 3)

In [78]:
# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(d,(9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])